In [1]:
# import the required libraries for data wrangling

#data manipulation modules
import numpy as np
import pandas as pd

# data visualization modules
import matplotlib.pyplot as plt
import seaborn as sns

# warnings ignorance
import warnings
warnings.filterwarnings("ignore")

In [5]:
#initialize url for the data
url="https://data.kcmo.org/api/views/vsgj-uufz/rows.csv?accessType=DOWNLOAD"

In [6]:
# pass the data in the url into a pandas dataframe
data=pd.read_csv(url)
# display the first 10 rows of the data, to display the last 10 use data.tail()
data.head(10)

    Report_No Reported_Date Reported_Time  ...   Age Firearm Used Flag Location
0  KC21000006    01/01/2021         00:01  ...  43.0              True      NaN
1  KC21000048    01/01/2021         03:22  ...  52.0             False      NaN
2  KC21000077    01/01/2021         11:26  ...  41.0             False      NaN
3  KC21000391    01/03/2021         06:32  ...  23.0             False      NaN
4  KC21000410    01/03/2021         09:52  ...   NaN             False      NaN
5  KC21000574    01/04/2021         09:30  ...  26.0             False      NaN
6  KC21000696    01/04/2021         16:23  ...  38.0              True      NaN
7  KC21000806    01/05/2021         05:06  ...  48.0             False      NaN
8  KC21001032    01/05/2021         18:04  ...   NaN             False      NaN
9  KC21001082    01/05/2021         21:47  ...  40.0             False      NaN

[10 rows x 23 columns]

In [9]:
# check the shape of the data
data.shape
print("the data contains ", data.shape[0], "rows and",data.shape[1],"columns")

the data contains  59988 rows and 23 columns

In [11]:
# missing values
data.isna().sum()

Report_No                0
Reported_Date            0
Reported_Time            0
From_Date                0
From_Time                0
To_Date              40425
To_Time              40425
Offense                  0
IBRS                  5602
Description           5602
Beat                     1
Address                  0
City                     1
Zip Code              3876
Rep_Dist             11448
Area                     5
DVFlag                   0
Involvement              0
Race                  7230
Sex                   6448
Age                  14306
Firearm Used Flag        0
Location             12292
dtype: int64

In [12]:
#data summary
data.describe

<bound method NDFrame.describe of         Report_No  ...                                           Location
0      KC21000006  ...                                                NaN
1      KC21000048  ...                                                NaN
2      KC21000077  ...                                                NaN
3      KC21000391  ...                                                NaN
4      KC21000410  ...                                                NaN
...           ...  ...                                                ...
59983  KC21049172  ...  N GARLAND AVE and ROCHESTER AVE\nKANSAS CITY 6...
59984  KC21055427  ...                                                NaN
59985  KC21055342  ...  4200  EUCLID AVE\nKANSAS CITY 64130\n(39.05032...
59986  KC21050812  ...  5200  E 41ST ST\nKANSAS CITY 64130\n(39.051287...
59987  KC21053969  ...                                                NaN

[59988 rows x 23 columns]>

In [13]:
# statistical summary
data.describe()

           Zip Code           Age
count  56112.000000  45682.000000
mean   64112.406295     37.758395
std     1009.232757     13.966912
min     6106.000000     18.000000
25%    64112.000000     27.000000
50%    64127.000000     35.000000
75%    64132.000000     46.000000
max    89104.000000     99.000000

In [15]:
# datatypes
data.dtypes

Report_No             object
Reported_Date         object
Reported_Time         object
From_Date             object
From_Time             object
To_Date               object
To_Time               object
Offense               object
IBRS                  object
Description           object
Beat                  object
Address               object
City                  object
Zip Code             float64
Rep_Dist              object
Area                  object
DVFlag                object
Involvement           object
Race                  object
Sex                   object
Age                  float64
Firearm Used Flag       bool
Location              object
dtype: object

In [16]:
# cleaning

# drop missing values 
data_1=data.dropna()
# data_ is the new clean dataset. to mantain we use the parametre inplace=true
data_1.head(5)

      Report_No  ...                                           Location
260  KC21029861  ...  1200  MCGEE ST\nKANSAS CITY 64106\n(39.099816,...
508  KC21000801  ...  8600  NE 112TH ST\nKANSAS CITY 64157\n(39.2965...
510  KC21010383  ...  1000  E 84TH TER\nKANSAS CITY 64131\n(38.97429...
511  KC21015726  ...  5400  N MERCIER ST\nKANSAS CITY 64118\n(39.192...
516  KC21005218  ...  7400  COLLEGE AVE\nKANSAS CITY 64132\n(38.9922...

[5 rows x 23 columns]

## Similar data

In [17]:
# to combine with the similar dataset , we may use concatenate or merge python functionns to combine the two datasets
url2='https://data.kcmo.org/api/views/pxaa-ahcm/rows.csv?accessType=DOWNLOAD'
# save the data in the url into a pandas dataframe
data_2=pd.read_csv(url2)
# display 5 samples of rows in the dataset
data_2.sample(5)

        Report_No  ...                                           Location
88975   190012581  ...  1801 W 41 ST #B2\nKANSAS CITY 64111\n(39.05434...
50066  KC19054000  ...  E 16TH TER and HARDESTY AVE\nKANSAS CITY 64127...
53851  KC19081539  ...  E 37TH ST and MONROE AVE\nKANSAS CITY\n(39.058...
5188   KC19024991  ...  6200  ST JOHN AVE\nKANSAS CITY\n(39.112123, -9...
55985  KC19085261  ...  4000  N BELMONT AVE\nKANSAS CITY 64117\n(39.16...

[5 rows x 23 columns]

In [19]:
# CLEANING THE SECOND DATA

#Drop missing values
data_2.dropna(inplace=True)
# display the clean data
data_2.head(5)

      Report_No  ...                                           Location
588  KC19077683  ...  5500  N BENNINGTON AVE\nKANSAS CITY 64119\n(39...
922  KC19022080  ...  E 62ND ST and PROSPECT AVE\nKANSAS CITY 64130\...
939  KC19020462  ...  6100  N MADISON AVE\nKANSAS CITY 64119\n(39.20...
949  KC19028879  ...  8500  E 59TH ST\nKANSAS CITY 64129\n(39.016853...
954  KC19031138  ...  6700  E FRONT ST\nKANSAS CITY 64120\n(39.13029...

[5 rows x 23 columns]

In [20]:
# understanding data2
data_2.describe

<bound method NDFrame.describe of         Report_No  ...                                           Location
588    KC19077683  ...  5500  N BENNINGTON AVE\nKANSAS CITY 64119\n(39...
922    KC19022080  ...  E 62ND ST and PROSPECT AVE\nKANSAS CITY 64130\...
939    KC19020462  ...  6100  N MADISON AVE\nKANSAS CITY 64119\n(39.20...
949    KC19028879  ...  8500  E 59TH ST\nKANSAS CITY 64129\n(39.016853...
954    KC19031138  ...  6700  E FRONT ST\nKANSAS CITY 64120\n(39.13029...
...           ...  ...                                                ...
84672  KC19090331  ...  8700  N MAIN ST\nKANSAS CITY 64155\n(39.252365...
84686  KC19097395  ...  12000  E 57TH TER\nKANSAS CITY 64133\n(39.0179...
84701  KC19088935  ...  6800  NE PLEASANT VALLEY RD\nKANSAS CITY 64119...
84713  KC19096181  ...  11200  COLLEGE AVE\nKANSAS CITY 64137\n(38.923...
84747  KC19090397  ...  7000  N WINCHESTER AVE\nKANSAS CITY 64119\n(39...

[8705 rows x 23 columns]>

In [21]:
# statistical summary of data2
data_2.describe()

           Zip Code          Age
count   8705.000000  8705.000000
mean   64083.122573    40.607582
std     1549.139419    15.176033
min     6411.000000    18.000000
25%    64114.000000    28.000000
50%    64127.000000    37.000000
75%    64133.000000    51.000000
max    66109.000000    99.000000

In [22]:
# data2 datatypes of columns
data_2.dtypes

Report_No             object
Reported_Date         object
Reported_Time         object
From_Date             object
From_Time             object
To_Date               object
To_Time               object
Offense               object
IBRS                  object
Description           object
Beat                  object
Address               object
City                  object
Zip Code             float64
Rep_Dist              object
Area                  object
DVFlag                object
Involvement           object
Race                  object
Sex                   object
Age                  float64
Firearm Used Flag       bool
Location              object
dtype: object

In [25]:
# the two dataset can now be combined in order to provide detailed analysis

all_data=pd.concat([data_1, data_2], ignore_index=True)

In [27]:
# displaying the first 5 rows of the combined data
all_data.head(5)

    Report_No  ...                                           Location
0  KC21029861  ...  1200  MCGEE ST\nKANSAS CITY 64106\n(39.099816,...
1  KC21000801  ...  8600  NE 112TH ST\nKANSAS CITY 64157\n(39.2965...
2  KC21010383  ...  1000  E 84TH TER\nKANSAS CITY 64131\n(38.97429...
3  KC21015726  ...  5400  N MERCIER ST\nKANSAS CITY 64118\n(39.192...
4  KC21005218  ...  7400  COLLEGE AVE\nKANSAS CITY 64132\n(38.9922...

[5 rows x 23 columns]

In [28]:
# summary of the combined data
all_data.describe

<bound method NDFrame.describe of         Report_No  ...                                           Location
0      KC21029861  ...  1200  MCGEE ST\nKANSAS CITY 64106\n(39.099816,...
1      KC21000801  ...  8600  NE 112TH ST\nKANSAS CITY 64157\n(39.2965...
2      KC21010383  ...  1000  E 84TH TER\nKANSAS CITY 64131\n(38.97429...
3      KC21015726  ...  5400  N MERCIER ST\nKANSAS CITY 64118\n(39.192...
4      KC21005218  ...  7400  COLLEGE AVE\nKANSAS CITY 64132\n(38.9922...
...           ...  ...                                                ...
18000  KC19090331  ...  8700  N MAIN ST\nKANSAS CITY 64155\n(39.252365...
18001  KC19097395  ...  12000  E 57TH TER\nKANSAS CITY 64133\n(39.0179...
18002  KC19088935  ...  6800  NE PLEASANT VALLEY RD\nKANSAS CITY 64119...
18003  KC19096181  ...  11200  COLLEGE AVE\nKANSAS CITY 64137\n(38.923...
18004  KC19090397  ...  7000  N WINCHESTER AVE\nKANSAS CITY 64119\n(39...

[18005 rows x 23 columns]>

CONCLUSION
Any detailed analysis, prediction, and visualizations can be now performed on the combined dataset which is;
1. clear

2. complete

3. clean